SFX_JUMP         EQU $1
SFX_SUPERBALL    EQU $2
SFX_STOMP        EQU $3
SFX_GROW         EQU $4
SFX_COIN         EQU $5
SFX_INJURY       EQU $6
SFX_BUMP         EQU $7
SFX_1UP          EQU $8
SFX_GIRA         EQU $9
SFX_TIMERTICK    EQU $A
SFX_FLOWER       EQU $B

SFX_EXPLOSION    EQU $1
SFX_BRICKSHATTER EQU $2
SFX_DEATHCRY     EQU $3
SFX_FIREBREATH   EQU $4
